import { getServerAuthSession } from "~/server/auth";

import "~/styles/globals.css";

import { Inter, Shrikhand, Raleway } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { Navbar } from "./_components/navbar";
import { Footer } from "./_components/footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const shrikhand = Shrikhand({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-shrikhand',
})

const raleway = Raleway({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-raleway',
})

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();

  return (
    <TRPCReactProvider>
      <html lang="en" className="bg-cover bg-white bg-topo-pattern h-screen">
        <head>
          <title>NUHOC Gear Locker</title>
        </head>
        <body className={`font-sans ${inter.variable} ${shrikhand.variable} ${raleway.variable} h-full w-full min-h-full flex flex-col justify-between`}>
          <Navbar loggedIn={!!session} />
          <div className=" bg-white w-full bg-opacity-85 grow">
            <div className=" h-full py-8 px-4 md:px-16 lg:px-40">{children}</div>
          </div>
          <Footer />
        </body>
      </html>
    </TRPCReactProvider>
  );
}
