name: Lint+Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "redacted"
      NEXTAUTH_SECRET: "redacted"
      GOOGLE_CLIENT_ID: "redacted"
      GOOGLE_CLIENT_SECRET: "redacted"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Build
        run: npm run build
